### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/anonymous_github#45]
Hi all,

I am working on the new version of Anonymous Github. I am making good progress.

Where is a preview of the current version:
<img width="1760" alt="Screenshot 2021-03-10 at 10 20 19" src="https://user-images.githubusercontent.com/5577568/110615896-350b2d80-8194-11eb-8f14-5cf8d7af0283.png">

# Changes

- Complete rewrite using NodeJS and MongoDB (instead of python and the file system)
- Focus on reducing the number of request to GitHub (for speed and reduce the Github token usage)
- Better anonymization, e.g., all paths are now anonymized (#20, #40)
- Two anonymization methods:
  - *Stream*: as the current version when a file is requested, the file is downloaded from Github. Bigger files are now supported (#33).
  - *Download* (new): the complete repository is downloaded when anonymized.  It has better performance, reduces the token usage but increases disk usage. This option is only available for repositories less than 10mb.
- More anonymization options:  
  - Remove all links
  - Removes all images
  - Render PDF (#39)
  - Render Notbook (#32)
- New page for anonymizing a repository
  - include a preview
  - select the branch
  - select options
- Dashboard to list all your anonymized repositories. It will be possible to import your previous repository.
- It uses now ace.js to render the code which offer a much better reading experience
- You must be logged to be able to anonymize a repository

# TODOs
- [x] Edit repository configuration
- [x] FAQ
- [ ] Evaluate the disk usage of the new approach (storage is expensive)
- [x] Handle repository expiration
- [x] Automatic update of the repository when a new commit is pushed
- [x] support Github page on the same branch
- [x] test the import of the current repositories
- [x] improve error message
- [ ] improve design
- [ ] replicate database
Any suggestion or comments are welcome

**Comment by tdurieux** [comment]
I'm considering a download button however this feature requires a lot of processing (anonymize all the files) and storage (for all the original and anonymized files, and the download zip). I m not sure that I can offer this. An option would be to offer it as a paid option.

**Comment by tdurieux** [comment]
The beta version of the v2 is available here: https://beta.durieux.me/.
Please try it and find potential problems.

**Comment by micahjsmith** [comment]
@tdurieux did a quick try of v2, thanks for your work!

* absolutely love the ability to see all of your projects in one place (/dashboard)
* suggestion: add expiration date column to the dashboard
* regression: some file types are no longer rendered, such as `MANIFEST.in` which is shown as plain text in v1 but in v2 shows `The file type is not supported. Anonymous GitHub cannot handle it.`
* typo: in `Annoymize repository` -> "Anonymize" (in button on dashboard, same typo in navbar)
* typo: in `Display the number of line of code in the reposiotry` -> "repository"
* type: in `PDF are not anonymized` -> "PDFs"
* a bit confusing that the file view for some file types has a cursor. I see you are using Ace editor, is this what the read-only view looks like? As a reader, I would prefer there there is no cursor and that the display does not afford editing, similar to how markdown files are displayed. I presume you are using Ace to make syntax highlighting easier? But I don't think as a reader there is much advantage to this view beyond the static file view that GitHub shows for example.
* 404: accessing my profile (/profile) gives a 404
* design: from the dashboard view, might want to move the logged-in user's name to the far right of the topbar, this is more customary location

**Comment by tdurieux** [comment]
@micahjsmith Thanks a lot for the feedback.

Yes, there were a lot of typos, I fixed a lot of them today. Sorry about that.

> suggestion: add expiration date column to the dashboard
Done 

> regression: some file types are no longer rendered, such as MANIFEST.in which is shown as plain text in v1 but in v2 shows The file type is not supported. Anonymous GitHub cannot handle it.

I now use a predefined list of file extensions to determine if a file is a text file. I don't know if it is the best way to do it. I am still reflecting on this. I did this to reduce server usage but I don't know if it is required.

> a bit confusing that the file view for some file types has a cursor.
 
I decided to use Ace editor compared to simple syntax highlighting because it offers some interesting features even for reading the code, such as line number, matching brackets, ... I removed the cursor. You can have a look to see if it is better. If I found a better way to display the code in the future it would be easy to change.

> `/profile` -> 404.
 I added the page today. The page contains the default anonymization settings.
 
 > design: from the dashboard view, might want to move the logged-in user's name to the far right of the topbar, this is more customary location

I still need to work on this. The "support me" button makes it a little bit more complicated.

**Comment by micahjsmith** [comment]
> I now use a predefined list of file extensions to determine if a file is a text file. 

this seems reasonable to me. However there is a long tail of file extensions that are actually plaintext and still relevant files that would not pass your allowlist. So perhaps there can be a fallback in this case? For example, apply the anonymization and show a download link for the anonymized file for the user to view in their own editor.

> I removed the cursor

this now looks better to me personally

> I added the page today. The page contains the default anonymization settings.

nice idea|! one note: currently pressing "save" has no visual cue on the page, may want to add a notification or some other indicator.

**Comment by delanohelio** [comment]
@tdurieux 
- That new version is amazing. Thank you!

In a quick tour, I found an issue in the claim message that did not disappear when I click on the button to claim. You can see in the gif attached.

![beta](https://user-images.githubusercontent.com/2471543/113870878-98e43e80-97b2-11eb-863f-a29cb0cf688a.gif)

**Comment by tdurieux** [comment]
The v2 is online. Enjoy :partying_face:

**Comment by aarezzou** [comment]
Hi!
Right now I can only see an older version of my repo through the anonymous link. Is there any way I can fix this?

Thanks!

**Comment by tdurieux** [comment]
@aarezzou did you enable the option: auto update?

**Comment by aarezzou** [comment]
It's fixed now. The problem was that it was set to the wrong branch.

**Comment by aarezzou** [comment]
The new version is great. Thanks!
Just one thought: will .jpg files be supported? I was able to see them before, but not anymore.

**Comment by tdurieux** [comment]
It is an option by default the images are not displayed because I cannot anonymize them. You can enable them in the option.

**Comment by aarezzou** [comment]
Got it. Thanks.

**Comment by faustomilletari** [comment]
@tdurieux I see you have limited the anonymization to run only on files with a certain extension. that's a good idea except in my opinion you could also include files without any extension at all. The default LICENSE file doesn't usually have one but it does contain usually very identifiable details. 

#480 #493 highlight this problem.

I have tried adding .txt to LICENSE and the anonymization does work. URL removal works even without the extension .txt but actual regex-based anonymization does run on LICENSE only if we add an extension to it.
